### ISSUE TITLE
PhantomJS upgrade to 2.0.0

### ISSUE THREAD

**Issue by przemekperon** [danielboendergaard/phantom-pdf#7]
There is an issue with phantomjs prior to 2.0.0 with web fonts not being rendered correctly. More about the issue: https://github.com/ariya/phantomjs/issues/10592

Please could you upgrade the attached phantomjs version to 2.0.0:
https://github.com/bprodoehl/phantomjs/releases/tag/v2.0.0-20150528

Thanks

**Comment by stefanneubig** [comment]
+1

**Comment by danielboendergaard** [comment]
I have been looking into this, but I did not update due to not having an official build. Since this supposed to be a drop-in library I'm not really a big fan of having to install packages via apt-get which the build you linked requires. However, I am willing to give it a go and i have made a dev branch alias to try it out for now. Just use the `1.0.*@dev` version in your `composer.json` file and you will get the version with PhantomJS 2.0.

Please give it a try and let me know if it works out for you :)

**Comment by rettigd** [comment]
The version of phantomjs included doesn't work on my machine. I have a mac, but I think this would be an issue for Windows too. Also, if running on AWS you have to do your own build right now. Can you make the location of bin configurable so it can be optionally loaded from another location for non supported installs?

Thanks

**Comment by danielboendergaard** [comment]
@rettigd As of `v0.7.1` the binary can now be set in the config file :)

**Comment by rettigd** [comment]
@danielboendergaard Thank you very much.

**Comment by vdh** [comment]
@danielboendergaard how do I set up the config file? The examples only mention how to configure the PDFGenerator, not the service provider

**Comment by danielboendergaard** [comment]
@vdh https://github.com/danielboendergaard/phantom-pdf/blob/master/src/config/config.php#L63
